stateDiagram-v2
    [*] --> STARTUP

    STARTUP --> STARTUP: LD / SR / SI / SW / SD
    STARTUP --> PLAY: P
    STARTUP --> [*]: QQ

    PLAY --> PLAY: Move cards
    PLAY --> PLAY: U / R
    PLAY --> PLAY: S / L
    PLAY --> STARTUP: Q
    PLAY --> [*]: QQ
